sudo: required
dist: trusty
language: ruby
rvm: 
  - 2.5.0
services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgis
before_script:
  - bash travis-install-pg10.sh
  - sudo mv postgis.control /usr/share/postgresql/10/extension/postgis.control
  - psql -c 'create database gojek_test;' -U postgres
  - psql -U postgres -c "create extension postgis"