language: ruby
rvm: 
  - 2.5.0
services:
  - postgresql
sudo: true
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
      - postgis
before_script:
  - psql -c 'create database gojek_test;' -U postgres
  - psql -U postgres -c "create extension postgis"